#!/bin/bash

# Script to submit interactive PBS jobs
# Copyright (C) 2015 Michael F. Herbst
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# A copy of the GNU General Public License can be found in the 
# file LICENCE or at <http://www.gnu.org/licenses/>.

WALLTIME="48" #hours
MEMORY="32" #gb
PROC="4" #processors

prelim_check() {
	if [ "$HOSTNAME" != "ccserv1" ]; then
		echo "Wrong host, use ccserv1" >&2
		exit 1
	fi
} && prelim_check

print_help() {
	cat << EOF
	$(basename $0) [ -h | --help | <Options> ]

Run an interactive job.

Options:
--np <np>       number of processors (Default: $PROC)
--wt <hours>    hours of walltime    (Default: $WALLTIME)
--mem <gb>      gb of memory         (Default: $MEMORY)

--no-screen-check
Do not check wheather qsubi is executed in a screen session.

NOTE: At the moment the --mem option sets both mem and vmem to
      the same value provided.
EOF
}

###########################################################

SCREENCHECK="yes"
while [ "$1" ]; do 
	case "$1" in 
		"-h"|"--help")
			print_help
			exit 0
			;;
		"--np")
			shift
			PROC=$1
			;;
		"--wt")
			shift
			WALLTIME="$1"
			;;
		"--mem")
			shift
			MEMORY="$1"
			;;
		"--no-screen-check")
			SCREENCHECK="no"
			;;
		*)
			echo "Unknown arg: $1" >&2
			exit 1
	esac
	shift
done

if [[ -z "$STY" && "$SCREENCHECK" != "no" ]]; then
	echo "No screen session active. Run within screen or supply --no-screen-check" >&2
	exit 1
fi

#PMEM=$((MEMORY/PROC))
#qsub -l "nodes=1:ppn=$PROC" -l "walltime=${WALLTIME}:00:00" -l "mem=${MEMORY}gb" -l "pmem=${PMEM}gb" -I
qsub -l "nodes=1:ppn=$PROC" -l "walltime=${WALLTIME}:00:00" -l "vmem=${MEMORY}gb" -l "mem=${MEMORY}gb"  -I
