#!/usr/bin/env python3
# vi: set et ts=4 sw=4 sts=4:

# Script to provide user interface for qchem jobscript generation
# Copyright (C) 2017 Michael F. Herbst, Manuel Hodecker, Marvin Hoffmann
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# A copy of the GNU General Public License can be found in the 
# file LICENCE or at <http://www.gnu.org/licenses/>.

from orca.orca_script_builder import orca_script_builder
from queuing_system.jobscript_builder import builder_main
from queuing_system.pbs import pbs

# This is a jobscript builder to send ORCA jobs
# using the PBS queuing system
qsys=pbs()
builder_main(orca_script_builder(qsys), qsys)

